import mongoose from "mongoose";

const TeamMemberSchema = new mongoose.Schema(
  {
    name: { type: String, default: "", trim: true },
    role: { type: String, default: "", trim: true },
    imageUrl: { type: String, default: "", trim: true },
    imageAlt: { type: String, default: "", trim: true },
    order: { type: Number, default: 0 },
  },
  { _id: false },
);

const homeHero = {
  homeHeroImageUrl: { type: String, default: "", trim: true },
  homeHeroImageAlt: { type: String, default: "", trim: true },
  homeHeroBadgeText: { type: String, default: "", trim: true },
  homeHeroTitleLine1: { type: String, default: "", trim: true },
  homeHeroTitleLine2: { type: String, default: "", trim: true },
  homeHeroDescription: { type: String, default: "", trim: true },
  homeHeroPrimaryCtaLabel: { type: String, default: "", trim: true },
  homeHeroPrimaryCtaHref: { type: String, default: "", trim: true },
  homeHeroSecondaryCtaLabel: { type: String, default: "", trim: true },
  homeHeroSecondaryCtaHref: { type: String, default: "", trim: true },
};

const servicesHero = {
  servicesHeroImageUrl: { type: String, default: "", trim: true },
  servicesHeroImageAlt: { type: String, default: "", trim: true },
  servicesHeroBadgeText: { type: String, default: "", trim: true },
  servicesHeroTitleLine1: { type: String, default: "", trim: true },
  servicesHeroTitleLine2: { type: String, default: "", trim: true },
  servicesHeroDescription: { type: String, default: "", trim: true },
  servicesHeroPrimaryCtaLabel: { type: String, default: "", trim: true },
  servicesHeroPrimaryCtaHref: { type: String, default: "", trim: true },
  servicesHeroSecondaryCtaLabel: { type: String, default: "", trim: true },
  servicesHeroSecondaryCtaHref: { type: String, default: "", trim: true },
};

const homeKeyServices = {
  homeKeyServicesEyebrow: { type: String, default: "", trim: true },
  homeKeyServicesHeadline: { type: String, default: "", trim: true },
  homeKeyServicesIntro: { type: String, default: "", trim: true },
  homeKeyServicesC1Title: { type: String, default: "", trim: true },
  homeKeyServicesC1Body: { type: String, default: "", trim: true },
  homeKeyServicesC1CtaLabel: { type: String, default: "", trim: true },
  homeKeyServicesC1CtaHref: { type: String, default: "", trim: true },
  homeKeyServicesC1ImageUrl: { type: String, default: "", trim: true },
  homeKeyServicesC1ImageAlt: { type: String, default: "", trim: true },
  homeKeyServicesC2IconLabel: { type: String, default: "", trim: true },
  homeKeyServicesC2Title: { type: String, default: "", trim: true },
  homeKeyServicesC2Body: { type: String, default: "", trim: true },
  homeKeyServicesC2PriceLabel: { type: String, default: "", trim: true },
  homeKeyServicesC2Price: { type: String, default: "", trim: true },
  homeKeyServicesC2ImageUrl: { type: String, default: "", trim: true },
  homeKeyServicesC2ImageAlt: { type: String, default: "", trim: true },
  homeKeyServicesC3Title: { type: String, default: "", trim: true },
  homeKeyServicesC3Body: { type: String, default: "", trim: true },
  homeKeyServicesC3CtaLabel: { type: String, default: "", trim: true },
  homeKeyServicesC3CtaHref: { type: String, default: "", trim: true },
  homeKeyServicesC3ImageUrl: { type: String, default: "", trim: true },
  homeKeyServicesC3ImageAlt: { type: String, default: "", trim: true },
  homeKeyServicesC4Title: { type: String, default: "", trim: true },
  homeKeyServicesC4Body: { type: String, default: "", trim: true },
  homeKeyServicesC4CtaLabel: { type: String, default: "", trim: true },
  homeKeyServicesC4CtaHref: { type: String, default: "", trim: true },
  homeKeyServicesC4ImageUrl: { type: String, default: "", trim: true },
  homeKeyServicesC4ImageAlt: { type: String, default: "", trim: true },
};

const aboutHero = {
  aboutHeroImageUrl: { type: String, default: "", trim: true },
  aboutHeroImageAlt: { type: String, default: "", trim: true },
  aboutHeroBadgeText: { type: String, default: "", trim: true },
  aboutHeroTitleLine1: { type: String, default: "", trim: true },
  aboutHeroTitleLine2: { type: String, default: "", trim: true },
  aboutHeroDescription: { type: String, default: "", trim: true },
  aboutHeroPrimaryCtaLabel: { type: String, default: "", trim: true },
  aboutHeroPrimaryCtaHref: { type: String, default: "", trim: true },
  aboutHeroSecondaryCtaLabel: { type: String, default: "", trim: true },
  aboutHeroSecondaryCtaHref: { type: String, default: "", trim: true },
};

const servicesKeyServices = {
  servicesKeyServicesEyebrow: { type: String, default: "", trim: true },
  servicesKeyServicesHeadline: { type: String, default: "", trim: true },
  servicesKeyServicesIntro: { type: String, default: "", trim: true },
  servicesKeyServicesC1Title: { type: String, default: "", trim: true },
  servicesKeyServicesC1Body: { type: String, default: "", trim: true },
  servicesKeyServicesC1CtaLabel: { type: String, default: "", trim: true },
  servicesKeyServicesC1CtaHref: { type: String, default: "", trim: true },
  servicesKeyServicesC1ImageUrl: { type: String, default: "", trim: true },
  servicesKeyServicesC1ImageAlt: { type: String, default: "", trim: true },
  servicesKeyServicesC2IconLabel: { type: String, default: "", trim: true },
  servicesKeyServicesC2Title: { type: String, default: "", trim: true },
  servicesKeyServicesC2Body: { type: String, default: "", trim: true },
  servicesKeyServicesC2PriceLabel: { type: String, default: "", trim: true },
  servicesKeyServicesC2Price: { type: String, default: "", trim: true },
  servicesKeyServicesC2ImageUrl: { type: String, default: "", trim: true },
  servicesKeyServicesC2ImageAlt: { type: String, default: "", trim: true },
  servicesKeyServicesC3Title: { type: String, default: "", trim: true },
  servicesKeyServicesC3Body: { type: String, default: "", trim: true },
  servicesKeyServicesC3CtaLabel: { type: String, default: "", trim: true },
  servicesKeyServicesC3CtaHref: { type: String, default: "", trim: true },
  servicesKeyServicesC3ImageUrl: { type: String, default: "", trim: true },
  servicesKeyServicesC3ImageAlt: { type: String, default: "", trim: true },
  servicesKeyServicesC4Title: { type: String, default: "", trim: true },
  servicesKeyServicesC4Body: { type: String, default: "", trim: true },
  servicesKeyServicesC4CtaLabel: { type: String, default: "", trim: true },
  servicesKeyServicesC4CtaHref: { type: String, default: "", trim: true },
  servicesKeyServicesC4ImageUrl: { type: String, default: "", trim: true },
  servicesKeyServicesC4ImageAlt: { type: String, default: "", trim: true },
};

const SiteSettingsSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      required: true,
      unique: true,
      default: "default",
      trim: true,
    },
    ...homeHero,
    ...homeKeyServices,
    ...servicesHero,
    ...servicesKeyServices,
    ...aboutHero,
    aboutHeritageHeadline: { type: String, default: "", trim: true },
    aboutHeritageBody: { type: String, default: "", trim: true },
    aboutHeritageStat1Value: { type: String, default: "", trim: true },
    aboutHeritageStat1Label: { type: String, default: "", trim: true },
    aboutHeritageStat2Value: { type: String, default: "", trim: true },
    aboutHeritageStat2Label: { type: String, default: "", trim: true },
    aboutHeritageImageCaption: { type: String, default: "", trim: true },
    aboutHeritageImageUrl: { type: String, default: "", trim: true },
    aboutHeritageImageAlt: { type: String, default: "", trim: true },
    aboutEngineersHeadline: { type: String, default: "", trim: true },
    aboutEngineersIntro: { type: String, default: "", trim: true },
    aboutEngineersCtaLabel: { type: String, default: "", trim: true },
    aboutEngineersCtaHref: { type: String, default: "", trim: true },
    aboutCtaHeadline: { type: String, default: "", trim: true },
    aboutCtaBody: { type: String, default: "", trim: true },
    aboutCtaButtonLabel: { type: String, default: "", trim: true },
    aboutCtaButtonHref: { type: String, default: "", trim: true },
    aboutCtaBackgroundImageUrl: { type: String, default: "", trim: true },
    aboutCtaBackgroundImageAlt: { type: String, default: "", trim: true },
    aboutTestimonialsHeadline: { type: String, default: "", trim: true },
    servicesStandardHeadline: { type: String, default: "", trim: true },
    servicesStandardBullet1: { type: String, default: "", trim: true },
    servicesStandardBullet2: { type: String, default: "", trim: true },
    servicesStandardBullet3: { type: String, default: "", trim: true },
    servicesStandardPrimaryCtaLabel: { type: String, default: "", trim: true },
    servicesStandardPrimaryCtaHref: { type: String, default: "", trim: true },
    servicesStandardSecondaryCtaLabel: { type: String, default: "", trim: true },
    servicesStandardSecondaryCtaHref: { type: String, default: "", trim: true },
    servicesStandardWatermark: { type: String, default: "", trim: true },
    servicesStandardBannerImageUrl: { type: String, default: "", trim: true },
    servicesStandardBannerImageAlt: { type: String, default: "", trim: true },
    teamMembers: {
      type: [TeamMemberSchema],
      default: [],
    },
  },
  { timestamps: true },
);

export default mongoose.models.SiteSettings ||
  mongoose.model("SiteSettings", SiteSettingsSchema);
